---
title: "Recent Posts"
---

```{r setup, include=FALSE}
library(htmltools)
blurb_post <- function(latest = FALSE, title = "Untitled", pub_date = Sys.Date(), link = "#", abstract= "Loren ipsum...") {
  if (latest) {
    div(class = "jumbotron",
        h1(title,
           tag("small", pub_date)),
        p(class = "lead",
          abstract),
        p(a(class = "btn btn-primary btn-lg",
            href = link,
            "Read more...")))
  } else {
  div(class = paste0("panel panel-", ifelse(latest, "info", "primary")),
      div(class = "panel-heading",
          h3(class = "panel-title",
             title)),
      div(class = "panel-body",
          abstract,
          a(href = link, "Read more...")),
      div(class = "panel-footer",
          pub_date))
}}
```

```{r blurbs, echo=FALSE}
blurb_post(TRUE, "Anyone Who Had a Heart", "29 January 2017", "2017-01-anyone-who-had-a-heart.html",
           "One of my goals for the year is to blog at least once a month - and time is nearly up for January! I've got a couple of things I've started on, notably my \"quantified self\" data, though I'm still letting the data ramble. Inspired by Maëlle Salmon's Catan visualisation I thought I'd finish up a visualisation of Hearts that I poked at last weekend. 

I've played a fair bit of Hearts over the years, and occasionally wondered about visualising the results. I played two games last weekend with my parents; the following morning, left at home sick whilst everyone else went to the National Aquarium, I thought I'd give it a go.

I'm not convinced they particularly add anything, but sometimes you have to try in order to find out.")
blurb_post(FALSE, "Earthquake Excuses", "28 December 2016", "2016-12-earthquake-excuses.html",
           "After my first foray into earthquake data I poked around a bit more but didn't produce anything hugely revelatory. I thought I'd use the data though as an excuse to try out a couple of new things: zooming facets in ggplot2, and creating maps with Plotly.")
blurb_post(FALSE, "Election Transparency", "20 December 2016", "2016-12-election-transparency.html",
           "Despite the timing, this post is not about the recent sorry excuse for democracy in
North America. I've been looking into the results of the recent local body elections in New Zealand
that used Single Transferable Vote (STV), and have some reflections on the transparency of results.

Recommendations:
(1) All STV elections should provide the iteration report with the results.
(2) Councils and (especially) DHBs should do better responding to OIAs (including, but not limited to, avoiding breaking the law).")
blurb_post(FALSE, "Earthquake Depth", "18 November 2016", "2016-11-earthquake-depth.html",
           "There have been a number of interesting visualisations of this weeks earthquakes: I
particularly like Chris McDowall's,
but also Harkanwal Singh's.
Most of them focus on the two-dimensional geographic dimensions, which is important. A
notable exception is the pie graph showing
that nearly half of the energy released by NZ earthquakes in seven years came on Monday.

I haven't seen anything yet that gives a closer look at the depths of these earthquakes.
The depth of the epicentre has an effect on the energy and damage at the surface, so
this seems like an important factor. Some use colour to indicate depth, but it's hard
to get a feel for the distribution and variation. I thought it would be interesting to take
a look at the quakes with depth as the primary dimension.")
blurb_post(FALSE, "Simple To Vote", "8 November 2016", "2016-11-simple-to-vote.html",
           "Recently we had local body elections in New Zealand. (You may have heard.) Single Transferable Vote (STV) was used for 7 of the 67 territorial authorities (city and district councils), for 1 of the 11 regional councils, and for 19 of the 20 district health boards. STV is Simple To Vote, but it can also be Strenuous To Vet - understanding how the votes are counted and the results are calculated is much less intuitive than First Past the Post (FPP).

So here are some animations to hopefully make the process in New Zealand a little easier to understand.")
blurb_post(FALSE, "W[h]ither Local Democracy?", "14 October 2016", "2016-10-whither-local-democracy.html",
           "If you live in New Zealand you would have been hard pressed not to notice that we had
local body elections recently. It seems that all anyone can talk about is the turnout.
Is it all bad news?")
blurb_post(FALSE, "The Luminaries", "26 August 2016", "2016-08-the-luminaries.html",
           "Last year I read Eleanor Catton's award-winning yarn The Luminaries. I started a little project around it, which is temporarily stalled (watch this space), but recently a colleague remarked about the chapter lengths and I was reminded I had this data.

The novel has a number of structural constraints, one of which is that each of the 12 parts is half the length of the previous one.

Or are they?")
blurb_post(FALSE, "Unfamiliar Maps", "14 August 2016", "2016-08-unfamiliar-maps.html",
           "At least 3 people have booked flights to Sydney, Nova Scotia (population 30,000) intending to holiday in
New South Wales (two orders of magnitude larger). There are a number of cases like this of towns and cities
with larger and more well known doppelgangers. 
I thought it would be interesting to have a map that labelled the familiar names in the unfamiliar locations.")
blurb_post(FALSE, "Birthday Eve", "9 August 2016", "2016-08-birthday-eve.html",
           "Some time ago I had a thought - if you had a daughter and she was born on Christmas Eve or New Year's Eve, would you be tempted to name her Eve?")
```
